### ISSUE TITLE
Method reference to protected method in base class in other package fails with IllegalAccessError

### ISSUE THREAD

**Issue by mig35** [evant/gradle-retrolambda#227]
Hi.
Same issue as it was here: https://github.com/orfjackal/retrolambda/issues/89

I'm using RxJava and subscribe method.

.subscribe(aBoolean -> {}, throwable -> doOnError(throwable)) - working
.subscribe(aBoolean -> {}, this::doOnError) - NOT working

using "me.tatarka:gradle-retrolambda:3.2.4"

**Comment by akonior** [comment]
For me version `3.3.1` works. The newest version `3.4.0` not working.

**Comment by evant** [comment]
See https://github.com/evant/gradle-retrolambda/issues/219

**Comment by evant** [comment]
Should be fixed by `3.5.0`

**Comment by danielesegato** [comment]
I still experience this in `3.6.0`. Is it possible?

Android `View` class, lambda calling the `setMeasuredDimension(int, int)` protected method:

```java
// the lamnda declaration
measureCallback = this::setMeasuredDimension;
```

This is the (cleaned up) error I get at runtime:

> IllegalAccessError:  Method 'View.setMeasuredDimension(int, int)' is inaccessible to class 'MyCustomView$$Lambda$1'


```gradle

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.0'
        classpath 'me.tatarka:gradle-retrolambda:3.6.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

apply plugin: 'com.android.library'
apply plugin: 'me.tatarka.retrolambda'

android {
   // redacted
}
```

**Comment by dchupov** [comment]
I'm experiencing this exact issue using **3.5.0**. IllegalAccessError when referencing a protected method from the base class which is located in another package.

**Comment by Artan1s** [comment]
I'm experiencing this in 3.6.0 too.

**Comment by WonderCsabo** [comment]
I am also seeing this. :(

**Comment by jpalvarezl** [comment]
I have this issue with 3.6.1 too.

**Comment by kassim** [comment]
I have this n 3.7.0

**Comment by RuslanKham322** [comment]
I think, i located problem (if author did not do this earlier).
I have this project structure:
-package
--subpackage
---BaseClass.java
--Subclass.java
`BaseClass` has protected method `void someAction()`:
```java
public class BaseClass {
    protected void someAction() { }
}
```
`Subclass` inherits `BaseClass` and has method `public void runSomeAction()`, that uses lambda:
```java
public class Subclass extends BaseClass {
    public void runSomeAction() {
        final Runnable runnable = this::someAction;
        runnable.run();
    }
}
```
After clean run i have this generated class:
```java
final class Subclass$$Lambda$1 implements Runnable {
    private final Subclass arg$1;

    private Subclass$$Lambda$1(Subclass var1) {
        this.arg$1 = var1;
    }

    public void run() {
        Subclass.access$lambda$0(this.arg$1);
    }

    public static Runnable lambdaFactory$(Subclass var0) {
        return new Subclass$$Lambda$1(var0);
    }
}
```
All works good.

But after making any changes in `Subclass` and running project, generated class is regenerated:
```java
final class Subclass$$Lambda$1 implements Runnable {
    private final Subclass arg$1;

    private Subclass$$Lambda$1(Subclass var1) {
        this.arg$1 = var1;
    }

    public void run() {
        this.arg$1.someAction();
    }

    public static Runnable lambdaFactory$(Subclass var0) {
        return new Subclass$$Lambda$1(var0);
    }
}
```
And `this.arg$1.someAction();` produces `IllegalAccessError`.
After clean run all again becomes good.
